package PointOfSale;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;

/**
 * This is main class which cooperates with <code>DBConnection</code> and <code>Article</code> classes. For now
 * it is set to get data from mocked method <code>ResultSet</code> but is also ready to work with real PostgreSQL.
 * As for input it is necessary to enter codes by hand in the right place while application is running.
 * <code>PrintReceipt</code> method is responsible for simulation the output.
 * Some access specifiers are package-private or protected instead of private because of test class!
 * <p>
 * IMPORTANT!
 * If database is not connected even though exception will be thrown the application will work correctly.
 * <p>
 * EXAMPLE BAR-CODES:
 * 123
 * 456
 * 789
 * 01234567890123
 *
 * @author Bartlomiej Karbownik
 */

public class Seller_GUI extends JFrame {
    private JPanel pointOfSaleJPanel;
    protected JList listArticlesJList;
    protected JTextField idEnter;
    private JButton scanButton;
    private JButton exitPrintReceiptButton;
    private JTextArea sumTextArea;
    private JPanel yourArticlesJPanel;
    private JPanel workspaceJPanel;


    public Seller_GUI() {
        DBConnection.getDBConncetion();
        add(pointOfSaleJPanel);

        this.setTitle("Point of sale");
        this.setBounds(Toolkit.getDefaultToolkit().getScreenSize().width / 2 - 250, Toolkit.getDefaultToolkit().getScreenSize().height / 2 - 250, 250, 250);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.pack();

        scanButton.addActionListener(this::scanActionPerformed);
        exitPrintReceiptButton.addActionListener(this::exitActionPerformed);
    }

    protected List<Article> listOfArticles = new ArrayList<Article>();
    private DefaultListModel model = new DefaultListModel();
    protected double totalSum = 0;
    private DecimalFormat df = new DecimalFormat("0.00");


    void scanActionPerformed(ActionEvent e) {
        String id = idEnter.getText();
        try {
            if (id.equals(""))
                throw new InvalidBarCodeException();
            else {
                long idArticle = Long.parseLong(id);
                articleChecker(idArticle);
            }
        } catch (InvalidBarCodeException | NumberFormatException ex) {
            System.out.println("Invalid bar-code!");
            JOptionPane.showMessageDialog(pointOfSaleJPanel, "Invalid bar-code", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    void exitActionPerformed(ActionEvent e) {
        printReceipt();
        JOptionPane.showMessageDialog(pointOfSaleJPanel, df.format(totalSum) + " zł", "Amount to pay", JOptionPane.INFORMATION_MESSAGE);
        model.clear();
        listOfArticles.clear();
        totalSum = 0;
        sumTextArea.setText("0");
    }

    void articleChecker(long id) {
        ResultSet rs = null;
        long idArticle = 0L;
        try {
            /*
            *
            * You can use this in case of real database. Otherwise you will use mocked data from <code>DBConnection</code>.
            *
            rs = DBConnection.executeQuery("SELECT * FROM article WHERE id = " + id);
             */
            rs = DBConnection.executeQuery(String.valueOf(id));
            while (rs.next()) {
                idArticle = rs.getLong("id");
                String nameArticle = rs.getString("name");
                double costArticle = rs.getDouble("cost");

                System.out.println("Product found!");
                addToArticleList(idArticle, nameArticle, costArticle);
            }
            if (id != idArticle)
                throw new ProductNotFoundException();
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ProductNotFoundException e) {
            System.out.println("Product not found!");
            JOptionPane.showMessageDialog(pointOfSaleJPanel, "Product not found", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    void addToArticleList(long id, String articleName, double cost) {
        model.addElement(articleName + " " + cost + "zł");
        listArticlesJList.setModel(model);
        System.out.println("Product added to list!");
        totalSum += cost;
        sumTextArea.setText(df.format(totalSum));
        listOfArticles.add(new Article(id, articleName, cost));
    }

    protected void printReceipt() {
        System.out.println("RECEIPT: ");
        for (Article a : listOfArticles)
            System.out.println(a.getName() + " " + a.getCost());
        System.out.println("Total cost: " + df.format(totalSum) + " zł");
    }

    public static void main(String[] args) {
        new Seller_GUI().setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pointOfSaleJPanel = new JPanel();
        pointOfSaleJPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        yourArticlesJPanel = new JPanel();
        yourArticlesJPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        pointOfSaleJPanel.add(yourArticlesJPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        yourArticlesJPanel.setBorder(BorderFactory.createTitledBorder("Your articles"));
        final JLabel label1 = new JLabel();
        label1.setText("List of scanned Articles: ");
        yourArticlesJPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        listArticlesJList = new JList();
        yourArticlesJPanel.add(listArticlesJList, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(150, 50), new Dimension(150, 300), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Total sum: ");
        yourArticlesJPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        sumTextArea = new JTextArea();
        yourArticlesJPanel.add(sumTextArea, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(150, 50), new Dimension(150, 50), null, 0, false));
        workspaceJPanel = new JPanel();
        workspaceJPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        pointOfSaleJPanel.add(workspaceJPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        workspaceJPanel.setBorder(BorderFactory.createTitledBorder("Workspace"));
        final JLabel label3 = new JLabel();
        label3.setText("Type in a code:");
        workspaceJPanel.add(label3, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        workspaceJPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        idEnter = new JTextField();
        idEnter.setText("");
        workspaceJPanel.add(idEnter, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        scanButton = new JButton();
        scanButton.setText("Scan");
        workspaceJPanel.add(scanButton, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        exitPrintReceiptButton = new JButton();
        exitPrintReceiptButton.setText("Exit / Print receipt");
        workspaceJPanel.add(exitPrintReceiptButton, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(150, 150), new Dimension(150, 150), null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        workspaceJPanel.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer3 = new com.intellij.uiDesigner.core.Spacer();
        workspaceJPanel.add(spacer3, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pointOfSaleJPanel;
    }
}